version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Warsaw
  open-pull-requests-limit: 20
  assignees:
  - hpruszyn
  versioning-strategy: increase